services:
  todo-postgres:
    container_name: todo_postgres
    build:
      context: ./todo-postgres
    image: todo-postgres:1.0
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo1234
      - POSTGRES_DB=todo
    volumes:
      - postgres-data1:/var/lib/postgresql/data
  todo-storage-service:
    container_name: todo-storage-service
    build:
      context: ./todo-storage-service
      dockerfile: Dockerfile.dev
    image: todo-storage-service:1.0
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=todo-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo1234
    depends_on:
      - todo-postgres
  todo-rebbit-mq:
    container_name: todo-rmq
    image: rabbitmq:3.13.0-management
    ports:
      - 8080:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
  todo-storage-ingestion:
    container_name: todo-storage-ingestion
    build:
      context: todo-storage-ingestion
      dockerfile: ./Dockerfile
    image: todo-storage-ingestion:development
    command: sh /app/start.sh
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - todo-postgres
      - todo-rebbit-mq
  todo-cache-ingestion:
    container_name: todo-cache-ingestion
    build: todo-cache-ingestion
    image: todo-cache-ingestion:1.0
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - STORAGE_SERVICE_URL=${STORAGE_SERVICE_URL}
    depends_on:
      todo-rebbit-mq:
        condition: service_healthy
      todo-redis:
        condition: service_started
  todo-api-gateway:
    container_name: todo-api-gateway
    build: todo-api-gateway
    image: todo-api-gateway:1.0
    ports:
      - 3002:3002
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - STORAGE_SERVICE_URL=${STORAGE_SERVICE_URL}
    depends_on:
      - todo-storage-ingestion
      - todo-cache-ingestion
  todo-redis:
    container_name: todo-redis
    image: redis:7.2.4
  todo-cache-service:
    container_name: todo-cache-service
    build: todo-cache-service
    image: todo-cache-service:1.0
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - todo-redis
volumes:
  postgres-data1:
